package telegramBot.admin;

public enum AdminState {
    START,
    CHECK_ADMIN,
    PASSWORD_CHECK,
    GET_USER_LIST,
    GET_SELLER_LIST,
    GET_PRODUCT_LIST,
    BALANCE,
    HISTORY,
    NOTIFICATIONS,
    BLOCK_SELLER,
    BLOCK_SELLER_PROCESS,
    CATEGORY_CRUD,
    UNKNOWN_COMMAND,
    ADD_CATEGORY,
    ADDING_CATEGORY_PROCESS,
    EDIT_CATEGORY,
    EDITING_CATEGORY_PROCESS,
    DELETE_CATEGORY,
    DELETING_CATEGORY_PROCESS,
    ACTIVATE_CATEGORY,
    ACTIVATING_CATEGORY_PROCESS,
    RENAMING_CATEGORY_PROCESS,
    PROCESS_COMPLETED,
    SELLER_REQUEST,
    NONE
}
